// data.js
// Stores node and edge data for the graph

const nodes = [
    { data: { id: 'Basic Radio', type: 'band', years: '1985–1987' } },
    { data: { id: 'Operation Ivy', type: 'band', years: '1987–1989' } },
    { data: { id: 'Dance Hall Crashers', type: 'band', years: '1989' } },
    { data: { id: 'Downfall', type: 'band', years: '1989' } },
    { data: { id: 'Shaken 69', type: 'band', years: '1995' } },
    { data: { id: 'Devils Brigade', type: 'band', years: '2000–present' } },
    { data: { id: 'Rancid', type: 'band', years: '1991–present' } },
    { data: { id: 'Transplants', type: 'band', years: '1999–2003, 2004–2006, 2010–present' } },
    { data: { id: 'Blink‑182', type: 'band', years: '1992–present' } },
    { data: { id: 'Big Rig', type: 'band', years: '1993' } },
    { data: { id: 'Common Rider', type: 'band', years: '1999–2003' } },
    { data: { id: 'Classics of Love', type: 'band', years: '2008–2012, 2020–present' } },
    { data: { id: 'DOOM Regulator', type: 'band', years: '2023–present' } },
    { data: { id: 'The Crew', type: 'band', years: '2021–present' } },
    { data: { id: 'The Old Firm Casuals', type: 'band', years: '2010–present' } },
    { data: { id: 'The Used', type: 'band', years: '2000–present' } },
    { data: { id: 'Angels & Airwaves', type: 'band', years: '2005–present' } },
    { data: { id: 'Box Car Racer', type: 'band', years: '2001–2003' } },
    { data: { id: '+44', type: 'band', years: '2005–2009' } },
    { data: { id: 'Simple Creatures', type: 'band', years: '2019–2020' } },
    { data: { id: 'Alkaline Trio', type: 'band', years: '1996–present' } },
    { data: { id: 'The Aquabats', type: 'band', years: '1994–present' } },
    { data: { id: 'The Interrupters', type: 'band', years: '2011–present' } },
    { data: { id: 'Charger', type: 'band', years: '2018–present' } },
    { data: { id: 'Tim Armstrong', type: 'member', years: '1985–present' } },
    { data: { id: 'Matt Freeman', type: 'member', years: '1985–present' } },
    { data: { id: 'Jesse Michaels', type: 'member', years: '1987–present' } },
    { data: { id: 'Dave Mello', type: 'member', years: '1987–present' } },
    { data: { id: 'Erik Larsen', type: 'member', years: '1989–present' } },
    { data: { id: 'Joey Schaaf', type: 'member', years: '1989–present' } },
    { data: { id: 'Andrew Champion', type: 'member', years: '1989–present' } },
    { data: { id: 'Grant McIntire', type: 'member', years: '1989–present' } },
    { data: { id: 'Joel Wing', type: 'member', years: '1989–present' } },
    { data: { id: 'Pat Mello', type: 'member', years: '1989–present' } },
    { data: { id: 'Jason Hammon', type: 'member', years: '1989–present' } },
    { data: { id: 'Paul Jackson', type: 'member', years: '1995–present' } },
    { data: { id: 'Eric Din', type: 'member', years: '1995–present' } },
    { data: { id: 'Lars Nylander', type: 'member', years: '1995–present' } },
    { data: { id: 'Mike Park', type: 'member', years: '1995–present' } },
    { data: { id: 'DJ Bonebrake', type: 'member', years: '1977–present' } },
    { data: { id: 'Rob Milucky', type: 'member', years: '2000–present' } },
    { data: { id: 'Brett Reed', type: 'member', years: '1991–present' } },
    { data: { id: 'Joey Castillo', type: 'member', years: '1984–present' } },
    { data: { id: 'Spencer Pollard', type: 'member', years: '2005–present' } },
    { data: { id: 'Fletcher Dragge', type: 'member', years: '1988–present' } },
    { data: { id: 'Byron McCracken', type: 'member', years: '1988–present' } },
    { data: { id: 'Mike Muir', type: 'member', years: '1981–present' } },
    { data: { id: 'Lars Frederiksen', type: 'member', years: '1993–present' } },
    { data: { id: 'Branden Steineckert', type: 'member', years: '2000–present' } },
    { data: { id: 'Skinhead Rob', type: 'member', years: '1999–present' } },
    { data: { id: 'Travis Barker', type: 'member', years: '1996–present' } },
    { data: { id: 'Kevin Bivona', type: 'member', years: '2005–present' } },
    { data: { id: 'Mark Hoppus', type: 'member', years: '1992–present' } },
    { data: { id: 'Tom DeLonge', type: 'member', years: '1992–present' } },
    { data: { id: 'Scott Raynor', type: 'member', years: '1992–present' } },
    { data: { id: 'Matt Skiba', type: 'member', years: '1996–present' } },
    { data: { id: 'Doug Sangalang', type: 'member', years: '1993–present' } },
    { data: { id: 'Kevin Cross', type: 'member', years: '1993–present' } },
    { data: { id: 'Jeremy Goody', type: 'member', years: '1993–present' } },
    { data: { id: 'Brandon Riggen', type: 'member', years: '1993–present' } },
    { data: { id: 'Mass Giorgini', type: 'member', years: '1999–present' } },
    { data: { id: 'Dan Lumley', type: 'member', years: '1999–present' } },
    { data: { id: 'Sharif Dumani', type: 'member', years: '2020–present' } },
    { data: { id: 'Peter John Fontes', type: 'member', years: '2020–present' } },
    { data: { id: 'Mike Huguenor', type: 'member', years: '2008–2012' } },
    { data: { id: 'Morgan Herrell', type: 'member', years: '2008–2012' } },
    { data: { id: 'Max Feshbach', type: 'member', years: '2008–2012' } },
    { data: { id: 'Casey Watson', type: 'member', years: '2010–present' } },
    { data: { id: 'Paul Rivas', type: 'member', years: '2010–present' } },
    { data: { id: 'Gabe Gavriloff', type: 'member', years: '2010–present' } },
    { data: { id: 'Bert McCracken', type: 'member', years: '2000–present' } },
    { data: { id: 'Jeph Howard', type: 'member', years: '2000–present' } },
    { data: { id: 'Dan Whitesides', type: 'member', years: '2006–present' } },
    { data: { id: 'Joey Bradford', type: 'member', years: '2018–present' } },
    { data: { id: 'Justin Shekoski', type: 'member', years: '2015–2018' } },
    { data: { id: 'Quinn Allman', type: 'member', years: '2000–2015' } },
    { data: { id: 'David Kennedy', type: 'member', years: '2001–present' } },
    { data: { id: 'Ilan Rubin', type: 'member', years: '2011–present' } },
    { data: { id: 'Matt Rubano', type: 'member', years: '2019–present' } },
    { data: { id: 'Atom Willard', type: 'member', years: '2000–present' } },
    { data: { id: 'Ryan Sinn', type: 'member', years: '2005–2007' } },
    { data: { id: 'Matt Wachter', type: 'member', years: '2003–2019' } },
    { data: { id: 'Eddie Breckenridge', type: 'member', years: '2014' } },
    { data: { id: 'Shane Gallagher', type: 'member', years: '2005–2009' } },
    { data: { id: 'Craig Fairbaugh', type: 'member', years: '2005–2009' } },
    { data: { id: 'Carol Heller', type: 'member', years: '2005' } },
    { data: { id: 'Anthony Celestino', type: 'member', years: '2002–2003' } },
    { data: { id: 'Alex Gaskarth', type: 'member', years: '2019–present' } },
    { data: { id: 'Dan Andriano', type: 'member', years: '1997–present' } },
    { data: { id: 'Rob Doran', type: 'member', years: '1996–1997' } },
    { data: { id: 'Glenn Porter', type: 'member', years: '1996–2000' } },
    { data: { id: 'Mike Felumlee', type: 'member', years: '2000–2001' } },
    { data: { id: 'Derek Grant', type: 'member', years: '2001–2023' } },
    { data: { id: 'MC Bat Commander', type: 'member', years: '1994–present' } },
    { data: { id: 'Crash McLarson', type: 'member', years: '1994–present' } },
    { data: { id: 'Jimmy the Robot', type: 'member', years: '1997–present' } },
    { data: { id: 'Lars Frederiksen and the Bastards', type: 'band', years: '2001–2005' } },
    { data: { id: 'Gordy Carbone', type: 'member', years: '2001–present' } },
    { data: { id: 'Big Jay Bastard', type: 'member', years: '2001–present' } },
    { data: { id: 'Craig Leg', type: 'member', years: '2001–present' } },
    { data: { id: 'Scott Abels', type: 'member', years: '1989–present' } },
    { data: { id: 'Stomper 98', type: 'band', years: '1998–present' } },
    { data: { id: 'Holger', type: 'member', years: '1998–present' } },
    { data: { id: 'Sebi', type: 'member', years: '1998–present' } },
    { data: { id: 'Tommi', type: 'member', years: '1998–present' } },
    { data: { id: 'Phil', type: 'member', years: '1998–present' } },
    { data: { id: 'Lars (Stomper)', type: 'member', years: '1998–present' } },
    { data: { id: 'The Last Resort', type: 'band', years: '1980–present' } },
    { data: { id: 'Roi Pearce', type: 'member', years: '1980–present' } },
    { data: { id: 'Charlie Duggan', type: 'member', years: '1980–present' } },
    { data: { id: 'Andy Benfield', type: 'member', years: '1980–present' } },
    { data: { id: 'Graham Saxby', type: 'member', years: '1980–present' } },
    { data: { id: 'The Lawrence Arms', type: 'band', years: '1999–present' } },
    { data: { id: 'Chris McCaughan', type: 'member', years: '1993–present' } },
    { data: { id: 'Brendan Kelly', type: 'member', years: '1993–present' } },
    { data: { id: 'Neil Hennessy', type: 'member', years: '1999–present' } },
    { data: { id: 'Slapstick', type: 'band', years: '1993–1996' } },
    { data: { id: 'Dan Hanaway', type: 'member', years: '1993–present' } },
    { data: { id: 'Matt Stamps', type: 'member', years: '1993–present' } },
    { data: { id: 'Rob Kellenberger', type: 'member', years: '1993–present' } },
    { data: { id: 'Peter Anna', type: 'member', years: '1993–present' } },
    { data: { id: 'Tuesday', type: 'band', years: '1996–1999' } },
    { data: { id: 'Tyler Wiseman', type: 'member', years: '1998–present' } },
    { data: { id: 'The New Transit Direction', type: 'band', years: '1999–2006' } },
    { data: { id: 'Josh Asher', type: 'member', years: '1999–present' } },
    { data: { id: 'Jake Hawley', type: 'member', years: '1999–present' } },
    { data: { id: 'Andrew Carruthers', type: 'member', years: '1999–present' } },
    { data: { id: 'Levi Lebo', type: 'member', years: '1999–present' } },
    { data: { id: 'John Finnegan', type: 'member', years: '1999–present' } },
    { data: { id: 'U.K. Subs', type: 'band', years: '1976–present' } },
    { data: { id: 'Nine Inch Nails', type: 'band', years: '1988–present' } },
    { data: { id: 'Trent Reznor', type: 'member', years: '1988–present' } },
    { data: { id: 'Atticus Ross', type: 'member', years: '2016–present' } },
    { data: { id: 'Robin Finck', type: 'member', years: '1994–present' } },
    { data: { id: 'Alessandro Cortini', type: 'member', years: '2005–present' } },
    { data: { id: 'Taking Back Sunday', type: 'band', years: '1999–present' } },
    { data: { id: 'John Nolan', type: 'member', years: '1999–present' } },
    { data: { id: 'Adam Lazzara', type: 'member', years: '1999–present' } },
    { data: { id: 'Shaun Cooper', type: 'member', years: '1999–present' } },
    { data: { id: 'Mark O\'Connell', type: 'member', years: '1999–present' } },
    { data: { id: 'Fred Mascherino', type: 'member', years: '2003–present' } },
    { data: { id: 'Matthew Fazzi', type: 'member', years: '2008–present' } },
    { data: { id: 'Eddie Reyes', type: 'member', years: '1999–present' } },
    { data: { id: 'Antonio Longo', type: 'member', years: '1999–present' } },
    { data: { id: 'Jesse Lacey', type: 'member', years: '1999–present' } },
    { data: { id: 'Steven DeJoseph', type: 'member', years: '1999–present' } },
    { data: { id: 'All Time Low', type: 'band', years: '2003–present' } },
    { data: { id: 'Jack Barakat', type: 'member', years: '2003–present' } },
    { data: { id: 'Rian Dawson', type: 'member', years: '2003–present' } },
    { data: { id: 'Zack Merrick', type: 'member', years: '2003–present' } },
    { data: { id: 'Paramore', type: 'band', years: '2004–present' } },
    { data: { id: 'Hayley Williams', type: 'member', years: '2004–present' } },
    { data: { id: 'Taylor York', type: 'member', years: '2004–present' } },
    { data: { id: 'Zac Farro', type: 'member', years: '2004–present' } },
    { data: { id: 'Josh Farro', type: 'member', years: '2004–present' } },
    { data: { id: 'Jeremy Davis', type: 'member', years: '2004–present' } },
    { data: { id: 'Jason Bynum', type: 'member', years: '2004–present' } },
    { data: { id: 'Hunter Lamb', type: 'member', years: '2004–present' } },
    { data: { id: 'John Hembree', type: 'member', years: '2004–present' } },
    { data: { id: 'Hepcat', type: 'band', years: '1989–present' } },
    { data: { id: 'Alex Désert', type: 'member', years: '1989–present' } },
    { data: { id: 'Deston Berry', type: 'member', years: '1989–present' } },
    { data: { id: 'Efren Santana', type: 'member', years: '1989–present' } },
    { data: { id: 'Kincaid Smith', type: 'member', years: '1989–present' } },
    { data: { id: 'Lino Trujillo', type: 'member', years: '1989–present' } },
    { data: { id: 'Greg Narvas', type: 'member', years: '1989–present' } },
    { data: { id: 'NOFX', type: 'band', years: '1983–present' } },
    { data: { id: 'Fat Mike', type: 'member', years: '1983–present' } },
    { data: { id: 'Eric Melvin', type: 'member', years: '1983–present' } },
    { data: { id: 'El Hefe', type: 'member', years: '1991–present' } },
    { data: { id: 'Erik Sandin', type: 'member', years: '1983–present' } },
    { data: { id: 'Ricky Fitness', type: 'member', years: '2002–present' } },
    { data: { id: 'Eaglebones Falconhawk', type: 'member', years: '2006–present' } },
    { data: { id: 'Aimee Interrupter', type: 'member', years: '2011–present' } },
    { data: { id: 'Justin Bivona', type: 'member', years: '2011–present' } },
    { data: { id: 'Jesse Bivona', type: 'member', years: '2011–present' } },
    { data: { id: 'Andrew McGee', type: 'member', years: '2018–present' } },
    { data: { id: 'Jason Willer', type: 'member', years: '2018–present' } }
];

const edges = [
    { data: { id: 'e0', source: 'Tim Armstrong', target: 'Basic Radio', label: 'guitar/vocals (1985–1987)' } },
    { data: { id: 'e1', source: 'Matt Freeman', target: 'Basic Radio', label: 'bass (1985–1987)' } },
    { data: { id: 'e2', source: 'Jesse Michaels', target: 'Operation Ivy', label: 'lead vocals (1987–1989)' } },
    { data: { id: 'e3', source: 'Tim Armstrong', target: 'Operation Ivy', label: 'guitar/vocals (1987–1989)' } },
    { data: { id: 'e4', source: 'Matt Freeman', target: 'Operation Ivy', label: 'bass/vocals (1987–1989)' } },
    { data: { id: 'e5', source: 'Dave Mello', target: 'Operation Ivy', label: 'drums (1987–1989)' } },
    { data: { id: 'e6', source: 'Tim Armstrong', target: 'Dance Hall Crashers', label: 'vocals (1989)' } },
    { data: { id: 'e7', source: 'Matt Freeman', target: 'Dance Hall Crashers', label: 'guitar (1989)' } },
    { data: { id: 'e8', source: 'Erik Larsen', target: 'Dance Hall Crashers', label: 'drums (1989)' } },
    { data: { id: 'e9', source: 'Joey Schaaf', target: 'Dance Hall Crashers', label: 'keyboards (1989)' } },
    { data: { id: 'e10', source: 'Andrew Champion', target: 'Dance Hall Crashers', label: 'vocals (1989)' } },
    { data: { id: 'e11', source: 'Grant McIntire', target: 'Dance Hall Crashers', label: 'guitar (1989)' } },
    { data: { id: 'e12', source: 'Joel Wing', target: 'Dance Hall Crashers', label: 'bass (1989)' } },
    { data: { id: 'e13', source: 'Tim Armstrong', target: 'Downfall', label: 'vocals (1989)' } },
    { data: { id: 'e14', source: 'Matt Freeman', target: 'Downfall', label: 'bass (1989)' } },
    { data: { id: 'e15', source: 'Dave Mello', target: 'Downfall', label: 'drums (1989)' } },
    { data: { id: 'e16', source: 'Pat Mello', target: 'Downfall', label: 'guitar (1989)' } },
    { data: { id: 'e17', source: 'Jason Hammon', target: 'Downfall', label: 'guitar (1989)' } },
    { data: { id: 'e18', source: 'Tim Armstrong', target: 'Shaken 69', label: 'member (1995)' } },
    { data: { id: 'e19', source: 'Matt Freeman', target: 'Shaken 69', label: 'bass (1995)' } },
    { data: { id: 'e20', source: 'Paul Jackson', target: 'Shaken 69', label: 'member (1995)' } },
    { data: { id: 'e21', source: 'Eric Din', target: 'Shaken 69', label: 'member (1995)' } },
    { data: { id: 'e22', source: 'Lars Nylander', target: 'Shaken 69', label: 'member (1995)' } },
    { data: { id: 'e23', source: 'Mike Park', target: 'Shaken 69', label: 'member (1995)' } },
    { data: { id: 'e24', source: 'Dave Mello', target: 'Shaken 69', label: 'drums (1995)' } },
    { data: { id: 'e25', source: 'Matt Freeman', target: 'Devils Brigade', label: 'lead vocals/double bass (2000–present)' } },
    { data: { id: 'e26', source: 'Tim Armstrong', target: 'Devils Brigade', label: 'guitar (2000–present)' } },
    { data: { id: 'e27', source: 'DJ Bonebrake', target: 'Devils Brigade', label: 'drums (2000–present)' } },
    { data: { id: 'e28', source: 'Rob Milucky', target: 'Devils Brigade', label: 'guitar (2000)' } },
    { data: { id: 'e29', source: 'Brett Reed', target: 'Devils Brigade', label: 'drums (2000)' } },
    { data: { id: 'e30', source: 'Tim Armstrong', target: 'Rancid', label: 'vocals/guitar (1991–present)' } },
    { data: { id: 'e31', source: 'Matt Freeman', target: 'Rancid', label: 'bass/vocals (1991–present)' } },
    { data: { id: 'e32', source: 'Lars Frederiksen', target: 'Rancid', label: 'guitar/vocals (1993–present)' } },
    { data: { id: 'e33', source: 'Brett Reed', target: 'Rancid', label: 'drums (1991–2006)' } },
    { data: { id: 'e34', source: 'Branden Steineckert', target: 'Rancid', label: 'drums (2006–present)' } },
    { data: { id: 'e35', source: 'Tim Armstrong', target: 'Transplants', label: 'lead vocals/lead guitar (1999–present)' } },
    { data: { id: 'e36', source: 'Skinhead Rob', target: 'Transplants', label: 'lead vocals (1999–present)' } },
    { data: { id: 'e37', source: 'Travis Barker', target: 'Transplants', label: 'drums/percussion (2002–present)' } },
    { data: { id: 'e38', source: 'Kevin Bivona', target: 'Transplants', label: 'bass/keyboards (2011–present)' } },
    { data: { id: 'e39', source: 'Tim Armstrong', target: 'The Crew', label: 'vocals/guitar (2021–present)' } },
    { data: { id: 'e40', source: 'Matt Freeman', target: 'The Crew', label: 'bass (2021–present)' } },
    { data: { id: 'e41', source: 'Fletcher Dragge', target: 'The Crew', label: 'guitar (2021–present)' } },
    { data: { id: 'e42', source: 'Byron McCracken', target: 'The Crew', label: 'drums (2021–present)' } },
    { data: { id: 'e43', source: 'Mike Muir', target: 'The Crew', label: 'vocals (2021–present)' } },
    { data: { id: 'e44', source: 'Tim Armstrong', target: 'DOOM Regulator', label: 'vocals/guitar (2023–present)' } },
    { data: { id: 'e45', source: 'Jesse Michaels', target: 'DOOM Regulator', label: 'vocals (2023–present)' } },
    { data: { id: 'e46', source: 'Joey Castillo', target: 'DOOM Regulator', label: 'drums (2023–present)' } },
    { data: { id: 'e47', source: 'Spencer Pollard', target: 'DOOM Regulator', label: 'bass (2023–present)' } },
    { data: { id: 'e48', source: 'Mark Hoppus', target: 'Blink‑182', label: 'bass/vocals (1992–present)' } },
    { data: { id: 'e49', source: 'Tom DeLonge', target: 'Blink‑182', label: 'guitar/vocals (1992–2005; 2009–2015; 2022–present)' } },
    { data: { id: 'e50', source: 'Travis Barker', target: 'Blink‑182', label: 'drums (1998–2005; 2009–present)' } },
    { data: { id: 'e51', source: 'Scott Raynor', target: 'Blink‑182', label: 'drums (1992–1998)' } },
    { data: { id: 'e52', source: 'Matt Skiba', target: 'Blink‑182', label: 'guitar/vocals (2015–2022)' } },
    { data: { id: 'e53', source: 'Jesse Michaels', target: 'Big Rig', label: 'vocals (1993)' } },
    { data: { id: 'e54', source: 'Doug Sangalang', target: 'Big Rig', label: 'guitar (1993)' } },
    { data: { id: 'e55', source: 'Kevin Cross', target: 'Big Rig', label: 'guitar (1993)' } },
    { data: { id: 'e56', source: 'Jeremy Goody', target: 'Big Rig', label: 'bass (1993)' } },
    { data: { id: 'e57', source: 'Brandon Riggen', target: 'Big Rig', label: 'drums (1993)' } },
    { data: { id: 'e58', source: 'Jesse Michaels', target: 'Common Rider', label: 'guitar/vocals (1999–2003)' } },
    { data: { id: 'e59', source: 'Mass Giorgini', target: 'Common Rider', label: 'bass (1999–2003)' } },
    { data: { id: 'e60', source: 'Dan Lumley', target: 'Common Rider', label: 'drums (1999–2003)' } },
    { data: { id: 'e61', source: 'Jesse Michaels', target: 'Classics of Love', label: 'vocals (2008–2012; 2020–present)' } },
    { data: { id: 'e62', source: 'Mike Huguenor', target: 'Classics of Love', label: 'guitar (2008–2012)' } },
    { data: { id: 'e63', source: 'Morgan Herrell', target: 'Classics of Love', label: 'bass (2008–2012)' } },
    { data: { id: 'e64', source: 'Max Feshbach', target: 'Classics of Love', label: 'drums (2008–2012)' } },
    { data: { id: 'e65', source: 'Sharif Dumani', target: 'Classics of Love', label: 'guitar/bass (2020–present)' } },
    { data: { id: 'e66', source: 'Peter John Fontes', target: 'Classics of Love', label: 'drums (2020–present)' } },
    { data: { id: 'e67', source: 'Lars Frederiksen', target: 'The Old Firm Casuals', label: 'vocals/guitar (2010–present)' } },
    { data: { id: 'e68', source: 'Casey Watson', target: 'The Old Firm Casuals', label: 'bass/vocals (2010–present)' } },
    { data: { id: 'e69', source: 'Paul Rivas', target: 'The Old Firm Casuals', label: 'guitar (2010–present)' } },
    { data: { id: 'e70', source: 'Gabe Gavriloff', target: 'The Old Firm Casuals', label: 'drums (2010–present)' } },
    { data: { id: 'e71', source: 'Bert McCracken', target: 'The Used', label: 'lead vocals/piano (2000–present)' } },
    { data: { id: 'e72', source: 'Jeph Howard', target: 'The Used', label: 'bass/backing vocals (2000–present)' } },
    { data: { id: 'e73', source: 'Dan Whitesides', target: 'The Used', label: 'drums/backing vocals (2006–present)' } },
    { data: { id: 'e74', source: 'Joey Bradford', target: 'The Used', label: 'guitar/backing vocals (2018–present)' } },
    { data: { id: 'e75', source: 'Justin Shekoski', target: 'The Used', label: 'guitar/backing vocals (2015–2018)' } },
    { data: { id: 'e76', source: 'Quinn Allman', target: 'The Used', label: 'guitar/backing vocals (2000–2015)' } },
    { data: { id: 'e77', source: 'Tom DeLonge', target: 'Angels & Airwaves', label: 'lead vocals/guitars/keyboards (2005–present)' } },
    { data: { id: 'e78', source: 'David Kennedy', target: 'Angels & Airwaves', label: 'guitars/keyboards (2005–2014; 2018–present)' } },
    { data: { id: 'e79', source: 'Ilan Rubin', target: 'Angels & Airwaves', label: 'drums/percussion (2011–present); keyboards/guitars/bass (2014–present)' } },
    { data: { id: 'e80', source: 'Matt Rubano', target: 'Angels & Airwaves', label: 'bass/synthesizers (2019–present)' } },
    { data: { id: 'e81', source: 'Atom Willard', target: 'Angels & Airwaves', label: 'drums (2005–2011)' } },
    { data: { id: 'e82', source: 'Ryan Sinn', target: 'Angels & Airwaves', label: 'bass/backing vocals (2005–2007)' } },
    { data: { id: 'e83', source: 'Matt Wachter', target: 'Angels & Airwaves', label: 'bass/synthesizers (2007–2014; 2018–2019)' } },
    { data: { id: 'e84', source: 'Eddie Breckenridge', target: 'Angels & Airwaves', label: 'bass (2014)' } },
    { data: { id: 'e85', source: 'Tom DeLonge', target: 'Box Car Racer', label: 'vocals/guitar (2001–2003)' } },
    { data: { id: 'e86', source: 'Travis Barker', target: 'Box Car Racer', label: 'drums (2001–2003)' } },
    { data: { id: 'e87', source: 'David Kennedy', target: 'Box Car Racer', label: 'guitar (2001–2003)' } },
    { data: { id: 'e88', source: 'Anthony Celestino', target: 'Box Car Racer', label: 'bass (2002–2003)' } },
    { data: { id: 'e89', source: 'Mark Hoppus', target: '+44', label: 'vocals/bass (2005–2009)' } },
    { data: { id: 'e90', source: 'Travis Barker', target: '+44', label: 'drums (2005–2009)' } },
    { data: { id: 'e91', source: 'Shane Gallagher', target: '+44', label: 'lead guitar (2005–2009)' } },
    { data: { id: 'e92', source: 'Craig Fairbaugh', target: '+44', label: 'rhythm guitar (2005–2009)' } },
    { data: { id: 'e93', source: 'Carol Heller', target: '+44', label: 'vocals (2005)' } },
    { data: { id: 'e94', source: 'Mark Hoppus', target: 'Simple Creatures', label: 'vocals/bass/keyboards (2019–2020)' } },
    { data: { id: 'e95', source: 'Alex Gaskarth', target: 'Simple Creatures', label: 'vocals/guitars/keyboards (2019–2020)' } },
    { data: { id: 'e96', source: 'Matt Skiba', target: 'Alkaline Trio', label: 'guitar/vocals/bass (1996–present)' } },
    { data: { id: 'e97', source: 'Dan Andriano', target: 'Alkaline Trio', label: 'bass/vocals/guitar (1997–present)' } },
    { data: { id: 'e98', source: 'Atom Willard', target: 'Alkaline Trio', label: 'drums (2023–present; touring substitute 2000–2001)' } },
    { data: { id: 'e99', source: 'Rob Doran', target: 'Alkaline Trio', label: 'bass/backing vocals (1996–1997)' } },
    { data: { id: 'e100', source: 'Glenn Porter', target: 'Alkaline Trio', label: 'drums (1996–2000)' } },
    { data: { id: 'e101', source: 'Mike Felumlee', target: 'Alkaline Trio', label: 'drums (2000–2001)' } },
    { data: { id: 'e102', source: 'Derek Grant', target: 'Alkaline Trio', label: 'drums/percussion/backing vocals (2001–2023)' } },
    { data: { id: 'e103', source: 'MC Bat Commander', target: 'The Aquabats', label: 'vocals (1994–present)' } },
    { data: { id: 'e104', source: 'Crash McLarson', target: 'The Aquabats', label: 'bass/backing vocals (1994–present)' } },
    { data: { id: 'e105', source: 'Jimmy the Robot', target: 'The Aquabats', label: 'keyboards/saxophone/backing vocals (1997–present)' } },
    { data: { id: 'e106', source: 'Ricky Fitness', target: 'The Aquabats', label: 'drums/percussion/backing vocals (2002–present)' } },
    { data: { id: 'e107', source: 'Eaglebones Falconhawk', target: 'The Aquabats', label: 'guitar/backing vocals (2006–present)' } },
    { data: { id: 'e108', source: 'Travis Barker', target: 'The Aquabats', label: 'drums/percussion (1996–1998)' } },
    { data: { id: 'e109', source: 'Aimee Interrupter', target: 'The Interrupters', label: 'lead vocals (2011–present)' } },
    { data: { id: 'e110', source: 'Kevin Bivona', target: 'The Interrupters', label: 'guitar (2011–present)' } },
    { data: { id: 'e111', source: 'Justin Bivona', target: 'The Interrupters', label: 'bass (2011–present)' } },
    { data: { id: 'e112', source: 'Jesse Bivona', target: 'The Interrupters', label: 'drums (2011–present)' } },
    { data: { id: 'e113', source: 'Matt Freeman', target: 'Charger', label: 'bass/vocals (2018–present)' } },
    { data: { id: 'e114', source: 'Andrew McGee', target: 'Charger', label: 'guitar (2018–present)' } },
    { data: { id: 'e115', source: 'Jason Willer', target: 'Charger', label: 'drums (2018–present)' } },
    { data: { id: 'e116', source: 'Branden Steineckert', target: 'The Used', label: 'drums/backing vocals (2000–2006)' } },
    { data: { id: 'e117', source: 'Lars Frederiksen', target: 'Lars Frederiksen and the Bastards', label: 'vocals/lead guitar (2001–2005)' } },
    { data: { id: 'e118', source: 'Gordy Carbone', target: 'Lars Frederiksen and the Bastards', label: 'vocals (2001–2005)' } },
    { data: { id: 'e119', source: 'Big Jay Bastard', target: 'Lars Frederiksen and the Bastards', label: 'bass (2001–2005)' } },
    { data: { id: 'e120', source: 'Craig Leg', target: 'Lars Frederiksen and the Bastards', label: 'rhythm guitar (2001–2005)' } },
    { data: { id: 'e121', source: 'Scott Abels', target: 'Lars Frederiksen and the Bastards', label: 'drums (2001–2005)' } },
    { data: { id: 'e122', source: 'Holger', target: 'Stomper 98', label: 'saxophone (1998–present)' } },
    { data: { id: 'e123', source: 'Sebi', target: 'Stomper 98', label: 'vocals (1998–present)' } },
    { data: { id: 'e124', source: 'Tommi', target: 'Stomper 98', label: 'guitar (1998–present)' } },
    { data: { id: 'e125', source: 'Phil', target: 'Stomper 98', label: 'drums (1998–present)' } },
    { data: { id: 'e126', source: 'Lars (Stomper)', target: 'Stomper 98', label: 'bass (1998–present)' } },
    { data: { id: 'e127', source: 'Lars Frederiksen', target: 'Stomper 98', label: 'guitar (2017–present)' } },
    { data: { id: 'e128', source: 'Roi Pearce', target: 'The Last Resort', label: 'bass (1980–1982)' } },
    { data: { id: 'e129', source: 'Charlie Duggan', target: 'The Last Resort', label: 'guitar (1980–1982)' } },
    { data: { id: 'e130', source: 'Andy Benfield', target: 'The Last Resort', label: 'drums (1980–1982)' } },
    { data: { id: 'e131', source: 'Graham Saxby', target: 'The Last Resort', label: 'vocals (1980–1982)' } },
    { data: { id: 'e132', source: 'Lars Frederiksen', target: 'The Last Resort', label: 'guitar (2013–present)' } },
    { data: { id: 'e133', source: 'Chris McCaughan', target: 'The Lawrence Arms', label: 'guitar/vocals (1999–present)' } },
    { data: { id: 'e134', source: 'Brendan Kelly', target: 'The Lawrence Arms', label: 'bass/vocals (1999–present)' } },
    { data: { id: 'e135', source: 'Neil Hennessy', target: 'The Lawrence Arms', label: 'drums (1999–present)' } },
    { data: { id: 'e136', source: 'Brendan Kelly', target: 'Slapstick', label: 'vocals (1993–1996)' } },
    { data: { id: 'e137', source: 'Dan Andriano', target: 'Slapstick', label: 'bass/backing vocals (1993–1996)' } },
    { data: { id: 'e138', source: 'Dan Hanaway', target: 'Slapstick', label: 'trumpet/backing vocals (1993–1996)' } },
    { data: { id: 'e139', source: 'Matt Stamps', target: 'Slapstick', label: 'guitar (1993–1996)' } },
    { data: { id: 'e140', source: 'Rob Kellenberger', target: 'Slapstick', label: 'drums/backing vocals (1993–1996)' } },
    { data: { id: 'e141', source: 'Peter Anna', target: 'Slapstick', label: 'trombone (1993–1996)' } },
    { data: { id: 'e142', source: 'Dan Andriano', target: 'Tuesday', label: 'bass/vocals (1996–1999)' } },
    { data: { id: 'e143', source: 'Matt Stamps', target: 'Tuesday', label: 'guitar (1996–1999)' } },
    { data: { id: 'e144', source: 'Rob Kellenberger', target: 'Tuesday', label: 'drums/vocals (1996–1999)' } },
    { data: { id: 'e145', source: 'Tyler Wiseman', target: 'Tuesday', label: 'guitar (1998–1999)' } },
    { data: { id: 'e146', source: 'Josh Asher', target: 'The New Transit Direction', label: 'guitar/lead vocals (1999–2006)' } },
    { data: { id: 'e147', source: 'Jake Hawley', target: 'The New Transit Direction', label: 'guitar (1999–2006)' } },
    { data: { id: 'e148', source: 'Andrew Carruthers', target: 'The New Transit Direction', label: 'bass (1999–2002)' } },
    { data: { id: 'e149', source: 'Levi Lebo', target: 'The New Transit Direction', label: 'bass (2002–2004)' } },
    { data: { id: 'e150', source: 'John Finnegan', target: 'The New Transit Direction', label: 'bass (2004–2006)' } },
    { data: { id: 'e151', source: 'Dan Whitesides', target: 'The New Transit Direction', label: 'drums (1999–2006)' } },
    { data: { id: 'e152', source: 'Lars Frederiksen', target: 'U.K. Subs', label: 'guitar (1991)' } },
    { data: { id: 'e153', source: 'Trent Reznor', target: 'Nine Inch Nails', label: 'vocals/guitars/bass/keys (1988–present)' } },
    { data: { id: 'e154', source: 'Atticus Ross', target: 'Nine Inch Nails', label: 'keyboards/synthesizers (2016–present)' } },
    { data: { id: 'e155', source: 'Robin Finck', target: 'Nine Inch Nails', label: 'guitar/synthesizers/keys (1994–1996; 2013–present)' } },
    { data: { id: 'e156', source: 'Alessandro Cortini', target: 'Nine Inch Nails', label: 'bass/keys/guitars (2005–2008; 2013–present)' } },
    { data: { id: 'e157', source: 'Ilan Rubin', target: 'Nine Inch Nails', label: 'drums/percussion/bass/guitars/cello/keys (2008–2009; 2013–present)' } },
    { data: { id: 'e158', source: 'John Nolan', target: 'Taking Back Sunday', label: 'lead guitar/keyboards/vocals (1999–2003; 2010–present)' } },
    { data: { id: 'e159', source: 'Adam Lazzara', target: 'Taking Back Sunday', label: 'lead vocals (2001–present); bass (1999–2001)' } },
    { data: { id: 'e160', source: 'Shaun Cooper', target: 'Taking Back Sunday', label: 'bass (2001–2003; 2010–present)' } },
    { data: { id: 'e161', source: 'Mark O\'Connell', target: 'Taking Back Sunday', label: 'drums (2001–present)' } },
    { data: { id: 'e162', source: 'Matt Rubano', target: 'Taking Back Sunday', label: 'bass/backing vocals (2003–2010)' } },
    { data: { id: 'e163', source: 'Fred Mascherino', target: 'Taking Back Sunday', label: 'lead guitar/vocals (2003–2008)' } },
    { data: { id: 'e164', source: 'Matthew Fazzi', target: 'Taking Back Sunday', label: 'lead guitar/keyboards/vocals (2008–2010)' } },
    { data: { id: 'e165', source: 'Eddie Reyes', target: 'Taking Back Sunday', label: 'rhythm guitar (1999–2018)' } },
    { data: { id: 'e166', source: 'Antonio Longo', target: 'Taking Back Sunday', label: 'lead vocals (1999–2001)' } },
    { data: { id: 'e167', source: 'Jesse Lacey', target: 'Taking Back Sunday', label: 'bass/vocals (1999)' } },
    { data: { id: 'e168', source: 'Steven DeJoseph', target: 'Taking Back Sunday', label: 'drums (1999)' } },
    { data: { id: 'e169', source: 'Alex Gaskarth', target: 'All Time Low', label: 'lead vocals/rhythm guitar (2003–present)' } },
    { data: { id: 'e170', source: 'Jack Barakat', target: 'All Time Low', label: 'lead guitar/backing vocals (2003–present)' } },
    { data: { id: 'e171', source: 'Rian Dawson', target: 'All Time Low', label: 'drums/percussion (2003–present)' } },
    { data: { id: 'e172', source: 'Zack Merrick', target: 'All Time Low', label: 'bass/backing vocals (2003–present)' } },
    { data: { id: 'e173', source: 'Hayley Williams', target: 'Paramore', label: 'lead vocals/keyboards (2004–present)' } },
    { data: { id: 'e174', source: 'Taylor York', target: 'Paramore', label: 'guitar/keyboards/backing vocals (2009–present)' } },
    { data: { id: 'e175', source: 'Zac Farro', target: 'Paramore', label: 'drums/percussion (2004–2010; 2017–present)' } },
    { data: { id: 'e176', source: 'Josh Farro', target: 'Paramore', label: 'lead guitar/backing vocals (2004–2010)' } },
    { data: { id: 'e177', source: 'Jeremy Davis', target: 'Paramore', label: 'bass (2004–2015)' } },
    { data: { id: 'e178', source: 'Jason Bynum', target: 'Paramore', label: 'rhythm guitar/backing vocals (2004–2005)' } },
    { data: { id: 'e179', source: 'Hunter Lamb', target: 'Paramore', label: 'rhythm guitar/backing vocals (2006–2007)' } },
    { data: { id: 'e180', source: 'John Hembree', target: 'Paramore', label: 'bass (2005)' } },
    { data: { id: 'e181', source: 'Alex Désert', target: 'Hepcat', label: 'vocals (1989–present)' } },
    { data: { id: 'e182', source: 'Deston Berry', target: 'Hepcat', label: 'keyboards/vocals (1989–present)' } },
    { data: { id: 'e183', source: 'Efren Santana', target: 'Hepcat', label: 'saxophone (1989–present)' } },
    { data: { id: 'e184', source: 'Kincaid Smith', target: 'Hepcat', label: 'trumpet (1989–present)' } },
    { data: { id: 'e185', source: 'Lino Trujillo', target: 'Hepcat', label: 'bass (1989–present)' } },
    { data: { id: 'e186', source: 'Greg Narvas', target: 'Hepcat', label: 'drums (1989–present)' } },
    { data: { id: 'e187', source: 'Scott Abels', target: 'Hepcat', label: 'drums (past member)' } },
    { data: { id: 'e188', source: 'Fat Mike', target: 'NOFX', label: 'lead vocals/bass (1983–present)' } },
    { data: { id: 'e189', source: 'Eric Melvin', target: 'NOFX', label: 'guitar/lead and backing vocals (1983–present)' } },
    { data: { id: 'e190', source: 'El Hefe', target: 'NOFX', label: 'guitar/lead and backing vocals (1991–present)' } },
    { data: { id: 'e191', source: 'Erik Sandin', target: 'NOFX', label: 'drums (1983–1985; 1986–present)' } }
];

// Export for use in main.js
window.nodes = nodes;
window.edges = edges;
